name: Update key

on:
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes with rebase
        run: git pull origin main --rebase

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        env:
          SP_DC: ${{ secrets.SP_DC }}
          CHROME_BIN: '/usr/bin/google-chrome'
        run: node index.js

      - name: Commit and push updated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "token.json"
          message: "Automated update of key"
          default_author: "github_actions"
          push: true
